steps:
  #Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/runimage', '.']
  #Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/runimage']

- id: 'create-attestation'
  name: 'gcr.io/${_PROJECT_ID}/binauthz-attestation:latest'
  args:
    - '--artifact-url'
    - 'gcr.io/${_PROJECT_ID}/runimage:latest'
    - '--attestor'
    - 'projects/${_PROJECT_ID}/attestors/demo-attestor'
    - '--keyversion'
    - 'projects/${_PROJECT_ID}/locations/global/keyRings/key-ring-1/cryptoKeys/key-1/cryptoKeyVersions/1'

  #Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - run
  - deploy
  - cloudrunv1
  - --image
  - gcr.io/${_PROJECT_ID}/runimage
  - --region
  - us-central1
  - --allow-unauthenticated
images:
- gcr.io/${_PROJECT_ID}/runimage
substitutions:
  _PROJECT_ID: forward-emitter-352908
