steps:
  #Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/runimage', '.']
  #Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/runimage']

- id: 'attestion'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - beta
  - container
  - binauthz
  - attestations
  - sign-and-create
  - --artifact-url
  - 'gcr.io/${_PROJECT_ID}/runimage@(gcloud container images describe gcr.io/${_PROJECT_ID}/runimage:latest --format "value(image_summary.digest)")'
  - demo-attestor
  - --attestor-project
  - ${_PROJECT_ID}
  - --keyversion-project
  - ${_PROJECT_ID}
  - --keyversion-location
  - 'global'
  - --keyversion-keyring
  - 'key-ring-1'
  - --keyversion-key
  - 'key-1'
  - --keyversion
  - '1'

  #Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - run
  - deploy
  - cloudrunv1
  - --image
  - gcr.io/${_PROJECT_ID}/runimage
  - --region
  - us-central1
  - --allow-unauthenticated
images:
- gcr.io/${_PROJECT_ID}/runimage
substitutions:
  _PROJECT_ID: forward-emitter-352908
